import Foundation
func tableCreate()
{
    let helper : Helper = Helper()
    helper.createGuestRoleTable()
    helper.createGuestTable()
    helper.createAuthenticationTable()
    helper.createBedTypeTable()
    helper.createRoomTypeTable()
    helper.createRoomTable()
    helper.createHotelRoomTable()
    helper.createPaymentStatusTable()
    helper.createBookingStatusTable()
    helper.createBookingTable()
    helper.createLoginTable()
    helper.createPaymentTable()
    helper.createCancellationTable()
    helper.createFeedbackTable()
    helper.insertBedType()
    helper.insertRoomType()
    helper.insertBookingType()
    helper.insertPaymentType()
    helper.insertUserType()
    helper.adminData()
    helper.bookingData()
    helper.roomData()
    helper.hotelRoomData()
}
tableCreate()
let loginViewModel = LoginViewModel()
let loginView  = LoginView(loginViewModel: loginViewModel)
loginViewModel.setLoginView(loginView: loginView)
loginView.LoginInit()
